"""add remarks to user_documents

Revision ID: 698de4437ca6
Revises: ec15e839a931
Create Date: 2026-05-15 16:45:56.487372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '698de4437ca6'
down_revision: Union[str, Sequence[str], None] = 'ec15e839a931'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_documents', sa.Column('remarks', sa.String(), nullable=True))
    