"""add dob to user profile

Revision ID: 88dae4175082
Revises: 2746a4ac7d00
Create Date: 2026-05-03 17:12:40.932924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88dae4175082'
down_revision: Union[str, Sequence[str], None] = '2746a4ac7d00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('date_of_birth', sa.Date(), nullable=True))
   
    # ### end Alembic commands ###



